apiVersion: batch/v1
kind: Job
metadata:
  name: demo-job-console
spec:
  template:
    spec:
      containers:
        - name: job
          image: nginxinc/nginx-unprivileged@sha256:731f382bbad9a874f9f27db9c82d9e671e603e2210386a8e2b6da36cf336fa75
          command: ["sh", "-c", "echo Bonjour depuis mon Job OpenShift"]
      restartPolicy: Never